### ISSUE TITLE
Feature: User Authentication Endpoint

### ISSUE THREAD

**Issue by rockchalkwushock** [rockchalkwushock/note_dashboard#2]
## User Story

1. User should be able to signup for an account.
2. User should be able to login to become an _authenticated user_.
3. User should be able to **only** see his/her notes while authenticated.
4. User should be able to logout becoming unauthenticated.
5. User should **not** be able to access any data without being authorized against `passport` with `jsonwebtoken`.

## Endpoints

> Parent endpoint is `/api/v1/`

| Endpoint        | Type          | Info |
| ------------- |:----------:| -----:|
| `user/sign-up`           | POST        | Creates an authenticated user in database. |
| `user/sign-in`             | POST        |  Validates user credentials as a user in the database, gives user a JWT |
| ~`user/check-token`~   | ~POST~       |  ~Validates the user has a _valid_ JWT~ |

## Todo

- [x] Write tests for `/sign-up` route.
- [x] Write `/sign-up` route.
- [x] Write tests for `/sign-in` route.
- [x] Write `/sign-in` route.
- [x] ~Write tests for `/check-token` route.~
- [x] ~Write `/check-token` route.~

**Comment by rockchalkwushock** [comment]
# Status Update :chart_with_upwards_trend:

Tests for `/sign-up` route still need work making sure they return exactly what is expected on the **error** case.

Code available at: [03e7c7c](https://github.com/rockchalkwushock/note_dashboard/commit/03e7c7cd59ab776db3f5db12582bc43ea21bfe48).

Not sure why `travis` is not generating coverage files when they generate with no issues on my local machine, will need to investigate 😕 

Will finish these tests tomorrow & proceed to implementing `passport` services for the `/sign-in` route & write the tests for that route as well.

**Comment by rockchalkwushock** [comment]
## `this` chat 😆 :scream_cat: :confounded:

@katiebldwn 

Remember what I told you about the importance of knowing the context of `this` when using `function()` vs `=>`; here is an example of what I meant: **[MUST USE FUNCTION!!!](https://github.com/rockchalkwushock/note_dashboard/blob/03e7c7cd59ab776db3f5db12582bc43ea21bfe48/api/modules/user/model.js#L44)**.

If I were to initialize the callback to `.pre()` with a fat arrow function the context of `this` would pertain to the fat arrow function so I would not have access to _isModified_, _password_, & __hashPassword_ since these are exclusive prototypes & keys on the `UserSchema` object

```js
// .pre() is a prototype on the UserSchema object natively
// so it's context of this is already bound to UserSchema.
// http://mongoosejs.com/docs/api.html#schema_Schema-pre
UserSchema.pre('save' (next) => {
  // my context of this now points to the anonymous callback function.
  // NOT my UserSchema object.
  // this.isModified === undefined
  if (this.isModified('password')) {  
    // this.password & this._hashPassword === undefined
    this.password = this._hashPassword(this.password); 
    return next();
  }
  return next();
});
```

**Comment by rockchalkwushock** [comment]
# Status Update :chart_with_upwards_trend:

Not going to build the `/check-token` route, really no need for this unless decide to provide token to user that expires. Then need to check for a _valid token_.

Writing internal docs & will close this issue in the next commit.
