### ISSUE TITLE
Feature: Notes Endpoint

### ISSUE THREAD

**Issue by rockchalkwushock** [rockchalkwushock/note_dashboard#3]
## User Story

1. User should be able to create a note.
2. User should be able to update a note.
3. User should be able to delete a note.
4. User should be able to get a _single_ note.
5. User should be able to get _all_ notes.

## Endpoints

> Parent endpoint is `/api/v1/`

| Endpoint            | Type           | Info  |
| --------------- |:-------------:| -----:|
| `/notes/`          | POST    | Creates a note in user's profile. |
| `/notes/:id`      | PUT       | Updates a note in a user's profile by id. |
| `/notes/:id`      | DELETE | Deletes a note in a user's profile by id. |
| `/notes/:id`      | GET       | Reads a note by id from a user's profile. |
| `/notes/`          | GET        | Reads all notes from a user's profile. |

## Todo

- [x] Write tests for `POST: /notes/`.
- [x] Write `POST: /notes/` route.
- [x] Write tests for `PATCH: /notes/:id`.
- [x] Write `PATCH: /notes/:id` route.
- [x] Write tests for `DELETE: /notes/:id`.
- [x] Write `DELETE: /notes/:id` route.
- [x] Write tests for `GET: /notes/:id`.
- [x] Write `GET: /notes/:id` route.
- [x] Write tests for `GET: /notes/`.
- [x] Write `GET: /notes/` route.

**Comment by rockchalkwushock** [comment]
# Status Update :chart_with_upwards_trend:

First endpoint of `notes` feature has been added and tested: [aa3888](https://github.com/rockchalkwushock/note_dashboard/commit/aa3888a6277520898df90c502223a171252e7b7f).

I will finish this feature this evening...adulting must be done now 😩 

But I get to see my niece ❤️ so it's not all that bad.

**Comment by rockchalkwushock** [comment]
# Status Update :chart_with_upwards_trend:

All features have been added to the api. Will create internal and external documentation & then merge with `api` branch.
